[package]
name = "aoc_2019"
version = "0.1.0"
authors = ["Janosch Gräf <janosch@nimiq.com>"]
edition = "2018"

[dependencies]
aoc-runner = "0.3.0"
aoc-runner-derive = "0.3.0"
failure = "0.1.6"
itertools = "0.8.2"
num = "0.2.0"
nalgebra = "0.19.0"
regex = "1.3.1"
num-traits = "0.2.10"
